Create Alert View
TeamLetrando/Letrando pull request #46
Opened 2021-09-20 15:10 UTC by kellyanenogueira1

2021-09-21 17:05 UTC, lidianegb commented on Letrando/Letrando/Shared/Assets.xcassets/alert_mascot.imageset/Contents.json
> +      "filename" : "dog2.pdf",
O nome da imagem pode ser mais descritivo, por exemplo: `mascotAlertScreen`. (Você é mais criativa do que eu kkk)

2021-09-21 17:12 UTC, lidianegb requested changes

2021-09-21 17:12 UTC, lidianegb commented on Letrando/Letrando/View/Alert/AlertView.swift
> +        message.numberOfLines = 0
O `número 0` pode ser substituído por `.zero`, fica melhor visualmente e evita esses `números mágicos`.

2021-09-21 17:12 UTC, lidianegb commented on Letrando/Letrando/Controller/Alert/AlertViewController.swift
> +    let alertView = AlertView()
Segundo definições da equipe, as variáveis precisam ser `lazy` sempre que possível. E os elementos da classe também precisam ser privados caso sejam utilizados apenas internamente.
`private lazy var alertView = AlertView()`

2021-09-21 17:12 UTC, lidianegb commented on Letrando/Letrando/Shared/Assets.xcassets/alert_mascot.imageset/Contents.json
> +      "filename" : "dog2.pdf",
O nome da imagem pode ser mais descritivo, por exemplo: mascotAlertScreen. (Você é mais criativa do que eu kkk)

2021-09-21 21:33 UTC, ronaldogomes96 approved these changes

2021-09-21 21:33 UTC, ronaldogomes96 commented on Letrando/Letrando/Utils/Localizable/LocalizableBundle.swift
> +    case alertMessage
Nesse caso, ja que são de telas diferentes, ou separar por espaços ou com o comentário MARK. Deixar dessa forma dificulta a leitura e Organização.

2021-09-21 21:33 UTC, ronaldogomes96 commented on Letrando/Letrando/View/Alert/AlertView.swift
> +        self.setupView()
Acredito que nao precisa deste self

2021-09-21 21:33 UTC, ronaldogomes96 commented on Letrando/Letrando/View/Alert/AlertView.swift
> +    private lazy var mascot: UIImageView = {
Acredito que mascot seja um nome de variável muito vago. Quem ler ele não sabe se é imagem, imageView, label ou qualquer outra coisa. Seria melhor deixar explicito o nome da variável

2021-09-21 21:33 UTC, ronaldogomes96 commented on Letrando/Letrando/View/Alert/AlertView.swift
> +    private lazy var message: UILabel = {
Mesmo comentario do anterior, especificar melhor o nome da variável.

2021-09-21 21:33 UTC, ronaldogomes96 commented on Letrando/Letrando/View/Alert/AlertView.swift
> +        NSLayoutConstraint.activate([
Evitar estes numeros mágicos. Melhor seria criar uma enum ou struct com essas variáveis, e novamente com nomes bem explicativos

2021-09-21 21:33 UTC, ronaldogomes96 commented on Letrando/Letrando/View/Alert/AlertView.swift
> +        backgroundColor = UIColor.lightGreenBackgroundLetrando
Acho que nao precisa do UIColor não?

2021-09-22 14:05 UTC, lidianegb approved these changes

2021-09-23 00:33 UTC, merged