Create onboarding
TeamLetrando/Letrando pull request #56
Opened 2021-10-07 12:27 UTC by kellyanenogueira1

2021-10-07 13:18 UTC, lidianegb requested changes

2021-10-07 13:18 UTC, lidianegb commented on Letrando/Letrando/Controller/Alert/AlertViewController.swift
> +       // transitionSearch()
Essa função tá comentada pq? se ela não está sendo usada deveria remover

2021-10-07 13:18 UTC, lidianegb commented on Letrando/Letrando/Controller/Onboarding/OnboardingViewController.swift
> +    private lazy var initialPage: Int = .zero
Acho que essa variável poderia ser mais clara.` initialPage` passa uma impressão que ela guarda a página inicial, mas, pelo que entendi, ela guarda o índice da página atual. Então poderia ser `currentIndexPage` ou algo parecido.

2021-10-07 14:08 UTC, ronaldogomes96 approved these changes

2021-10-07 14:08 UTC, ronaldogomes96 commented on Letrando/Letrando/Controller/Alert/AlertViewController.swift
> +       // transitionSearch()
Retirar o código comentado!

2021-10-07 14:08 UTC, ronaldogomes96 commented on Letrando/Letrando/Controller/Onboarding/OnboardingViewController.swift
> +    func configure() {
Especificar melhor o nome da função, dizer o que ela configura

2021-10-07 14:08 UTC, ronaldogomes96 commented on Letrando/Letrando/Controller/Onboarding/OnboardingViewController.swift
> +class OnboardingViewController: UIPageViewController {
Seria melhor usar o protocolo ViewCodable nao?

2021-10-07 14:08 UTC, ronaldogomes96 commented on Letrando/Letrando/Controller/Onboarding/OnboardingViewController.swift
> +        view.addSubview(pageControl)
Com o protocolo view codable esses addSubviews ficariam na função especifica

2021-10-13 13:44 UTC, lidianegb approved these changes

2021-10-13 13:56 UTC, ronaldogomes96 requested changes

2021-10-13 13:56 UTC, ronaldogomes96 commented on Letrando/Letrando/Controller/Onboarding/OnboardingViewController.swift
> +        previewButton.isHidden = currentIndexPage == .zero ? true : false
Essa linha pode ser trocada por 
(currentIndexPage == .zero)

2021-10-13 13:56 UTC, ronaldogomes96 commented on Letrando/Letrando/Controller/Onboarding/OnboardingViewController.swift
> +
Linha de espaço em branco que não deveria existir

2021-10-13 13:56 UTC, ronaldogomes96 commented on Letrando/Letrando/Controller/Onboarding/OnboardingViewController.swift
> +            page = currentIndexPage < pages.count - 1 ? pages[currentIndexPage + 1] : nil
Colocar parênteses na sentença de condicional ajuda na leitura da expressão.

2021-10-13 13:56 UTC, ronaldogomes96 commented on Letrando/Letrando/Controller/Onboarding/OnboardingViewController.swift
> +            page = currentIndexPage == .zero ? nil : pages[currentIndexPage - 1]
Mesma coisa dos parênteses.

2021-10-13 14:21 UTC, ronaldogomes96 approved these changes

2021-10-13 14:22 UTC, merged