Fixbug/navegacao
TeamLetrando/Letrando pull request #57
Opened 2021-10-18 23:52 UTC by lidianegb

2021-10-19 13:45 UTC, kellyanenogueira1 commented on Letrando/Letrando/Game/ViewController/Search+Gestures.swift
> +        gameView?.lettersStackView.subviews.forEach { (view) in
Lint não reclamou dos parênteses em (view)? 🤔

2021-10-19 14:01 UTC, kellyanenogueira1 approved these changes

2021-10-19 14:14 UTC, lidianegb commented on Letrando/Letrando/Game/ViewController/Search+Gestures.swift
> +        gameView?.lettersStackView.subviews.forEach { (view) in
Não amiga, não reclamou. Esse código já estava, só alterei a `gameView` pra ser opcional e ai adicionei o ponto de interrogação nessa linha.

2021-10-19 14:53 UTC, ronaldogomes96 requested changes

2021-10-19 14:53 UTC, ronaldogomes96 commented on Letrando/Letrando/Game/Router/GameRouter.swift
> +    init(resultSceneFactory: SceneFactory, wordResult: String?, navigationController: UINavigationController?)
Porque ele tem que receber o resultSceneFactory? Na verdade, a ideia do router é que deve ter todos os factorys criados e instanciados nele propios, e não injetados.

2021-10-19 14:53 UTC, ronaldogomes96 commented on Letrando/Letrando/Game/Router/GameRouter.swift
> +    private var wordResult = String()
Porque essa inicialização, se poderia ser optional, e injetado via construtor?

2021-10-19 14:53 UTC, ronaldogomes96 commented on Letrando/Letrando/Game/SceneFactory/GameSceneFactory.swift
> +    lazy var randomWord = JsonData().randomWord()
Essa variável precisa ser publica?

2021-10-19 14:53 UTC, ronaldogomes96 commented on Letrando/Letrando/Game/View/GameView.swift
> +protocol GameViewProtocol {
Que tal invés de usar esse protocolo, poderíamos usar um padrão, tipo o ViewCodable ou ate mesmo nem usar, ja que precisamos de uma UIView msm de verdade la na controller?

2021-10-19 14:53 UTC, ronaldogomes96 commented on Letrando/Letrando/Game/View/GameView.swift
> +    private var animationKey = "showAnimationFeedback"
Esse conjunto de variáveis deveriam ser lazys

2021-10-19 14:53 UTC, ronaldogomes96 commented on Letrando/Letrando/Game/View/GameView.swift
> +    required convenience init(letters: [String]?) {
Trocar para o init normal, a gente ja tinha conversado sobre essas questões do init lembra? Se aplicaria nesse caso?

2021-10-19 14:53 UTC, ronaldogomes96 commented on Letrando/Letrando/Game/ViewController/SearchView+ARDelegate.swift
> +        addWord(letters: self.word?.breakInLetters() ?? [], plane: plane)
Precisa desse self explicito?? Acredito que isso pode causar um leak.

2021-10-19 14:53 UTC, ronaldogomes96 commented on Letrando/Letrando/Game/ViewController/SearchViewController.swift
> +    required convenience init(wordGame: Word?) {
Mesma questão do convinience.

2021-10-19 14:53 UTC, ronaldogomes96 commented on Letrando/Letrando/Game/ViewController/SearchViewController.swift
> +protocol GameViewControllerProtocol: UIViewController {
A função principal do protocolo da controller é a que chama o router. O que faz a chamada da controller. E eu não vi ela em nenhuma função. Deveria ter ela e essa ser a única função do protocolo. E quando for chamar o router, em actions, chama essa função. Isso ajuda nos testes. Alem disso ela não deve ser herdada de UIViewController, pois isso atrapalha nos testes. Precisamos olhar isso melhor, sei que a gente conversou de ser herdada de view controller, mais pensando nos testes e na ideia inicial do protocolo, nao vale a pena ser herdado de ViewController. De qualquer forma, o review da função principal ainda vale.

2021-10-19 14:53 UTC, ronaldogomes96 commented on Letrando/Letrando/Game/ViewController/SearchViewController.swift
> +    internal var gameView: GameView?
internal? A variavel por padrão é internal.

2021-10-19 14:53 UTC, ronaldogomes96 commented on Letrando/Letrando/Game/ViewController/SearchViewController.swift
> +        gameView?.addSubview(sceneView)
Eu sei que esta é a controller antiga, mais vale a pena usar um view codable, ou ate mesmo um loadView

2021-10-19 14:53 UTC, ronaldogomes96 commented on Letrando/Letrando/Game/ViewController/SearchViewController.swift
> +    func setup(with view: GameView, gameRouter: GameRouterLogic) {
To achando que essa função fica redundante, seria melhor deixar somente no loadView, e focar o protocolo na função de ação que ja tinha mencionado?

2021-10-19 14:53 UTC, ronaldogomes96 commented on Letrando/Letrando/Game/ViewController/SearchViewController.swift
> +        gameRouter?.startResult()
Tipo aqui, chamar a função do protocolo. Por questões de organização.

2021-10-19 14:53 UTC, ronaldogomes96 commented on Letrando/Letrando/Game/ViewController/SearchViewController.swift
> +        gameRouter?.backToHome()
Aqui também a questão do protocolo.

2021-10-19 14:53 UTC, ronaldogomes96 commented on Letrando/Letrando/Home/Router/HomeRouter.swift
> +    init(onboardingSceneFactory: SceneFactory,
Mesmo comentario que ja tinha falado no router anterior.

2021-10-19 14:53 UTC, ronaldogomes96 commented on Letrando/Letrando/Home/View/HomeView.swift
> +protocol HomeViewProtocol: UIView {
Nesse caso o protocolo faz sentido, com o delegate, porem nao concordo em herdar de UIView.

2021-10-19 14:53 UTC, ronaldogomes96 commented on Letrando/Letrando/Home/ViewController/HomeViewController.swift
> +protocol HomeViewControllerProtocol: UIViewController {
Mesmo comentário do review da controller anterior.

2021-10-19 14:53 UTC, ronaldogomes96 commented on Letrando/Letrando/Onboarding/Router/OnboardingRouter.swift
> +
Espaço desnecessário no fim da classe.

2021-10-19 14:53 UTC, ronaldogomes96 commented on Letrando/Letrando/Onboarding/SceneFatory/OnboardingSceneFactory.swift
> +        onboardingViewController.setup(onboardingRouter: instantiateOnboardingRouter())
Nessa parte poderia ser view o setup, que ja comentei anterior, ou poderia ser via injeção de dependência mesmo, porem é so uma escolha, não tem opção certa.

2021-10-19 14:53 UTC, ronaldogomes96 commented on Letrando/Letrando/Onboarding/View/PageView.swift
> +    private lazy var animationName = String()
Acredito que essas variáveis poderia ser so opcionais sem o lazy, melhor que instanciar com String().

2021-10-19 14:53 UTC, ronaldogomes96 commented on Letrando/Letrando/Onboarding/View/PageView.swift
> +final class PageView: UIView, ViewCodable {
Gostei desse final class. Poderia usa em todas as classes concretas que vem de protocolos e que não devem ser herdadas

2021-10-19 14:53 UTC, ronaldogomes96 commented on Letrando/Letrando/Onboarding/View/PageView.swift
> +    convenience init(animationName: String, message: String) {
Mesma questão do convenience init que ja tínhamos falado.

2021-10-19 14:53 UTC, ronaldogomes96 commented on Letrando/Letrando/Onboarding/ViewController/OnboardingViewController.swift
>      func configurePages() {
Essa função da bem longa, com talvez mais de uma responsabilidade. Alem disso ela deve estar publica?

2021-10-19 14:53 UTC, ronaldogomes96 commented on Letrando/Letrando/Onboarding/ViewController/OnboardingViewController.swift
>          if currentIndexPage == (pages.count - 1) {
Poderia ser usado um operador ternário nessa função.

2021-10-19 14:53 UTC, ronaldogomes96 commented on Letrando/Letrando/Onboarding/ViewController/PageViewController.swift
> +protocol PageViewControllerProtocol: UIViewController {
Mesmo comentario referente as protocolos de controllers

2021-10-19 14:53 UTC, ronaldogomes96 commented on Letrando/Letrando/Onboarding/ViewController/PageViewController.swift
> +    private let transitionTime = CGFloat(3)
Se tem inicialização deveria ser lazy.

2021-10-19 14:53 UTC, ronaldogomes96 commented on Letrando/Letrando/Result/Router/ResultRouter.swift
> +
Espaço desnecessário no fim da classe.

2021-10-19 14:53 UTC, ronaldogomes96 commented on Letrando/Letrando/Result/SceneFactory/ResultSceneFactory.swift
> +    convenience init(navigationController: UINavigationController?, wordResult: Word?) {
Questão do convenience init.

2021-10-19 14:53 UTC, ronaldogomes96 commented on Letrando/Letrando/Result/SceneFactory/ResultSceneFactory.swift
> +    required init(navigationController: UINavigationController?) {
Não entendi a necessidade de haver dois inits.

2021-10-19 14:53 UTC, ronaldogomes96 commented on Letrando/Letrando/Result/View/ResultView.swift
> +    required convenience init(wordResult: String) {
Também não entendi a situação desse convenience

2021-10-19 14:53 UTC, ronaldogomes96 commented on Letrando/Letrando/Shared/Router/MainRouter.swift
> +    required init(scene: UIWindowScene, homeSceneFatory: SceneFactory, navigationController: UINavigationController) {
Esse required é necessário quando o init vem do protocolo?

2021-10-19 14:53 UTC, ronaldogomes96 commented on Letrando/Letrando/Shared/Router/MainRouter.swift
> +    func startHome() {
Essa função tem mais responsabilidade que deveria, não esta somente "iniciando a home", pois ela faz muito trabalho de navigation. Seria melhor separar em duas funções.

2021-10-19 14:55 UTC, lidianegb commented on Letrando/Letrando/Game/Router/GameRouter.swift
> +    init(resultSceneFactory: SceneFactory, wordResult: String?, navigationController: UINavigationController?)
pq eu não sabia e vc não me falou

2021-10-19 14:58 UTC, lidianegb commented on Letrando/Letrando/Game/Router/GameRouter.swift
> +    private var wordResult = String()
Ela pode sim ser opcional, vou mudar. E ela está sendo injetada via construtor sim

2021-10-19 14:59 UTC, lidianegb commented on Letrando/Letrando/Game/SceneFactory/GameSceneFactory.swift
> +    lazy var randomWord = JsonData().randomWord()
precisa não. Já alterei

2021-10-19 15:01 UTC, lidianegb commented on Letrando/Letrando/Game/View/GameView.swift
> +protocol GameViewProtocol {
A ideia do protocolo foi vc mesmo que deu, já que o projeto é orientado a protocolos. E o protocolo eu posso definir variáveis e métodos que vão ser visíveis onde precisar e se eu usar o tipo UIView fica muito genérico.

2021-10-19 15:04 UTC, lidianegb commented on Letrando/Letrando/Game/View/GameView.swift
> +    private var animationKey = "showAnimationFeedback"
pra ser lazy elas precisam ser `var`. Os valores não mudam e seria desnecessário utilizar `var`.

2021-10-19 15:04 UTC, lidianegb commented on Letrando/Letrando/Result/SceneFactory/ResultSceneFactory.swift
> +    convenience init(navigationController: UINavigationController?, wordResult: Word?) {
é proibido usar?

2021-10-19 15:06 UTC, lidianegb commented on Letrando/Letrando/Result/SceneFactory/ResultSceneFactory.swift
> +    required init(navigationController: UINavigationController?) {
o required vem do protocolo e quando eu assino sou obrigada a implementar. Porém precisava de um init customizado para receber o wordResult então eu implemento o init customizado e chamo o obrigatório.

2021-10-19 15:06 UTC, lidianegb commented on Letrando/Letrando/Result/View/ResultView.swift
> +    required convenience init(wordResult: String) {
init customizado

2021-10-19 15:07 UTC, lidianegb commented on Letrando/Letrando/Shared/Router/MainRouter.swift
> +    required init(scene: UIWindowScene, homeSceneFatory: SceneFactory, navigationController: UINavigationController) {
isso

2021-10-19 15:09 UTC, lidianegb commented on Letrando/Letrando/Shared/Router/MainRouter.swift
> +    func startHome() {
a única coisa que ela tá fazendo é inicializar a Home, e as configurações que é setada na navigation são necessárias para a Home.

2021-10-21 12:32 UTC, ronaldogomes96 approved these changes

2021-10-21 12:33 UTC, merged