Create action in Lint.yml
TeamLetrando/Letrando pull request #58
Opened 2021-10-20 11:53 UTC by kellyanenogueira1

2021-10-20 12:21 UTC, ronaldogomes96 requested changes

2021-10-20 12:21 UTC, ronaldogomes96 commented on .github/workflows/Lint.yml
> +      - main
A branch TestFlight esta faltando.

2021-10-21 14:20 UTC, lidianegb approved these changes

2021-10-22 11:53 UTC, ronaldogomes96 approved these changes

2021-10-22 11:53 UTC, merged