Feature : Add game dog animation
TeamLetrando/Letrando pull request #62
Opened 2021-10-28 14:21 UTC by patysiq

### Summary
Adicionado animação cachorrinho na gameview.

### Details
Aguardando som.

### Related Task
Criar função que mostra mascote

Thank you for your review 😊

2021-10-28 14:41 UTC, lidianegb requested changes

2021-10-28 14:41 UTC, lidianegb commented on Letrando/Letrando.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = com.patriciasampaiosiqueira.Letrando;
é melhor deixar as configurações de bundle indentifier sem modificações

2021-10-28 14:41 UTC, lidianegb commented on Letrando/Letrando.xcodeproj/project.pbxproj
> +				PRODUCT_BUNDLE_IDENTIFIER = com.patriciasampaiosiqueira.Letrando;
A mesma coisa de cima, alterações de product bundle

2021-10-28 14:41 UTC, lidianegb commented on Letrando/Letrando/Letrando.entitlements
> +		<string>iCloud.com.patriciasampaio.FullMind</string>
Era pra ter essas alterações de iCloud mesmo?

2021-10-28 15:06 UTC, lidianegb requested changes

2021-10-28 15:06 UTC, lidianegb commented on Letrando/Letrando.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = 937MK3AF6X;
Desfazer esse tbm

2021-10-29 12:01 UTC, patysiq commented on Letrando/Letrando/Letrando.entitlements
> +		<string>iCloud.com.patriciasampaio.FullMind</string>
Resolvido. ok

2021-10-29 12:06 UTC, lidianegb approved these changes

2021-10-29 12:08 UTC, ronaldogomes96 approved these changes

2021-10-29 12:08 UTC, ronaldogomes96 commented on Letrando/Letrando/Game/View/GameView.swift
> +    private var isDogAnimated: Bool = false
Não precisa do :Bool pois o compilador ja entende que é um booleano, e alem disso se tem alguma inicialização é custume nosso ser lazy.

2021-10-29 13:29 UTC, patysiq commented on Letrando/Letrando/Game/View/GameView.swift
> +    private var isDogAnimated: Bool = false
vou modificar

2021-10-29 13:47 UTC, merged