[Fix] Change errors about sounds
TeamLetrando/Letrando pull request #69
Opened 2021-11-25 14:29 UTC by patysiq

### Summary
- Mudança para resolver problemas com controle de sons (onboarding e home)

2021-11-25 14:37 UTC, kellyanenogueira1 approved these changes

2021-11-25 22:07 UTC, lidianegb requested changes

2021-11-25 22:07 UTC, lidianegb commented on Letrando/Letrando.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = 937MK3AF6X;
melhor desfazer as alterações de pbxproj

2021-11-25 22:07 UTC, lidianegb commented on Letrando/Letrando/Game/View/GameView.swift
> +        if !userDefaults.bool(forKey: UserDefaultsKey.onboardingIsOn.rawValue) {
usa userDefaults.object pra verificar se aquela chave já esta registrada. Essa verificação do bool vai retornar false se a chave não existir

2021-11-26 11:32 UTC, lidianegb approved these changes

2021-11-26 11:32 UTC, merged